name: linter
on: [push]
jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest